Convert to Class and change config
yannickgloster/discord-10man pull request #33
Opened 2020-09-20 13:09 UTC by yannickgloster

- Changed the bot to be through a class and have a runner file
- Changed config to start support for multiple servers

Closes #31

2020-09-20 16:07 UTC, lexesjan requested changes

2020-09-20 16:07 UTC, lexesj commented on cogs/csgo.py
> +                           self.bot.servers[0]["RCON_password"], 'exec triggers/get5')
Typo, should be `server_password` should be `server_port`

2020-09-20 16:07 UTC, lexesjan commented on cogs/csgo.py
> +                           self.bot.servers[0]["RCON_password"],
Typo, same as above

2020-09-20 16:07 UTC, lexesjan commented on cogs/setup.py
> +                           self.bot.servers[0]["RCON_password"], f'say {message}')
Typo, same as above

2020-09-20 16:07 UTC, lexesjan commented on cogs/setup.py
> +                           self.bot.servers[0]["RCON_password"], 'removeallids')
Typo, same as above

2020-09-21 08:48 UTC, yannickgloster commented on cogs/csgo.py
> +                           self.bot.servers[0]["RCON_password"], 'exec triggers/get5')
Fixed in latest commit

2020-09-21 08:48 UTC, yannickgloster commented on cogs/setup.py
> +                           self.bot.servers[0]["RCON_password"], f'say {message}')
server_port

2020-09-21 08:49 UTC, yannickgloster commented on cogs/csgo.py
> +                           self.bot.servers[0]["RCON_password"],
Fixed in Commit

2020-09-21 08:49 UTC, yannickgloster commented on cogs/setup.py
> +                           self.bot.servers[0]["RCON_password"], 'removeallids')
Fixed in Commit

2020-09-21 11:51 UTC, lexesjan approved these changes
Looks good!

2020-09-21 11:52 UTC, merged